name: Test & Publish Docker Image

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      rabbitmq-streaming:
        image: pivotalrabbitmq/rabbitmq-stream
        env:
          RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_stream  advertised_host localhost"
        ports:
          - 5552:5552
          - 15672:15672
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2
      - name: Run tests
        run: make test
      - name: Upload code coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Publish Docker Image
        run: |
          set -x
          VERSION=latest
          export VERSION
          if [[ ! $GITHUB_REF =~ "/tags/" ]]
          then
            VERSION=dev
          fi
          make perf-test-docker-push
